### ISSUE TITLE
Beta Cycle Plans

### ISSUE THREAD

**Issue by Brett-Best** [cirruslabs/macos-image-templates#160]
Hello!

Just thought I'd make an issue to see if any consideration has been made for the upcoming beta cycle plans running from about June to September?

I'm hoping that it will be possible to create the following images:
- macOS 14.x with Xcode 16 betas
- macOS 15 betas with Xcode 16 betas

Thanks 🙂

**Comment by fkorotkov** [comment]
Pretty much like you outlined except we'll wait for the first public macOS 15 beta to start pushing the images. 🙌

**Comment by Brett-Best** [comment]
Cool! Fingers crossed putting Xcode 16 on macOS 14 image Just Works™️

**Comment by waddles** [comment]
While testing [sequoia 15.1 beta 2](https://github.com/cirruslabs/macos-image-templates/commit/ed0b1e4c151fbd620f2c891fdfa113b8107ec398) builds I found it fails toward the end of the vanilla builds when it tries to access the System Settings widget. There doesn't seem to be a way of navigating from the left search panel to the settings widgets in the right panel using only keystrokes in order to enable remote access.

Did you have the same problems when building the hosted image?

I found this [command for enabling remote access](https://github.com/sickcodes/osx-optimizer/blob/f5912e638212eb1f39512b5db888f5f65491c5f6/README.md#enable-remote-access-at-your-own-risk) for all users and was wondering if you think that is a suitable command to run instead of using keystrokes. I added it to our own templates and it succeeded but you should probably do your own testing.

**Comment by fkorotkov** [comment]
@waddles we don't do anything specific. The builds we have are automated:

https://github.com/cirruslabs/macos-image-templates/blob/24ff639c4d51c9e374df35434b39cf0aa3260424/.cirrus.yml#L46-L47

The only thing is that we build on a Sequoia host so Apple ID is working.
