### ISSUE TITLE
Headless VM images on Docker

### ISSUE THREAD

**Issue by SaadBazaz** [cirruslabs/macos-image-templates#177]
Two noob questions:
1. Does this work on Docker?
2. Are there any headless images available? I don't want to load the UI as I plan to run parallel CI/CD builds on resource-constraint machines.

**Comment by edigaryev** [comment]
>Does this work on Docker?

No, since Docker doesn't work directly on macOS, it requires Linux, and Linux in turn doesn't have access to Apple's [`Virtualization.Framework`](https://developer.apple.com/documentation/virtualization).

These VM images are meant to be ran with [Tart](https://tart.run/) and/or [Orchard](https://github.com/cirruslabs/orchard).

We also offer a managed solution in the form of [Cirrus Runners](https://cirrus-runners.app/), where you can also use these images.

>Are there any headless images available? I don't want to load the UI as I plan to run parallel CI/CD builds on resource-constraint machines.

These images can be made headless.

In case you're planning (or already using) Tart, just pass the `--no-graphics` command-line argument:

```
tart run --no-graphics <VM>
```

In case of Orchard, this is the default.

**Comment by SaadBazaz** [comment]
Sick. Thanks, @edigaryev. I'll consider this when building out infrastructure.
