### ISSUE TITLE
Minor template changes

### ISSUE THREAD

**Issue by naikrovek** [cirruslabs/macos-image-templates#72]
Deduplications and moving things around to slightly better places (I think.)

https://github.com/cirruslabs/macos-image-templates/blob/master/templates/base.pkr.hcl#L75
 * you set up DNS *after* you do a bunch of stuff requiring Internet connectivity.  Move this block to the top of this template or into the `vanilla` template, maybe?

https://github.com/cirruslabs/macos-image-templates/blob/master/templates/base.pkr.hcl#L38-L46

versus

https://github.com/cirruslabs/macos-image-templates/blob/master/templates/xcode.pkr.hcl#L42-L52

 * you don't need this twice, surely.  

The default shell for GitHub Actions steps which run in a shell is `bash`.  Everything you add to `/Users/admin/.zprofile` should probably also be added to `/Users/admin/.profile` so that Bash stuff doesn't fail due to a lack of configuration for that shell.  I'm not saying that all shells should be accommodated, only the GHA default.

https://github.com/cirruslabs/macos-image-templates/blob/master/templates/xcode.pkr.hcl#L138-L144

 * This block fails for me currently, and I'm not sure why.  Was this tested?

I don't have time to submit a PR to make this easier for you, sorry about that.  These are easy things, though.

**Comment by fkorotkov** [comment]
Addressing it in #73 except for GHA installation dublication. The [Xcode part](https://github.com/cirruslabs/macos-image-templates/blob/master/templates/xcode.pkr.hcl#L42-L52) is re-installing the runner since we sometimes build just the Xcode tag without rebuilding the base image.

As for the failing built of `xcode` variant, I did build an image today and it worked. Are you trying to build for the latest Xcode? Have you tried to run and ssh into the failed to build VM and see what `brew doctor` and `flutter doctor` print?

**Comment by naikrovek** [comment]
I did not SSH into the VM to see why those failed, Packer halts and destroys the VM before I can do so.  Obviously there are workarounds for this...  I'll see what's going on, obviously.

Another option (which I may adopt myself) is to adapt the runner building configuration that GitHub themselves use and switch it to use `tart` as the virtualization layer rather than Anka, which is what Microsoft uses.  In the tiny chance that you're not familiar with how GitHub build their images, here's the repo where they store their scripts to build their images: https://github.com/actions/runner-images/
